### ISSUE TITLE
Invalid URI Scheme

### ISSUE THREAD

**Issue by VoteAlex** [Dome8394/website#1]
`http://https://` is not a valid URI scheme, and thus the target cannot be opened.

https://github.com/Dome8394/website/blob/ce8a85042a8615e7341654900c1214906ae3f5b6/dist/index.html#L131
https://github.com/Dome8394/website/blob/ce8a85042a8615e7341654900c1214906ae3f5b6/dist/index.html#L149

**Comment by Dominik8394** [comment]
Thanks. Fixed it!
